const english = {
  language: 'english',
  home: 'Home',
  map: 'MAP',
  scheduleCalendar: 'Schedule Calendar',
  ourTeam: 'Our Team',
  settings: 'Settings',
  aboutUs: 'About Us',
  logoutText: 'Logout',
  upcoming: 'Upcoming',
  newInspection: 'New Inspection',
  pastInspection: 'Past Inspection',
  inspectionDetails: 'Inspection Details',
  placeOfMission: 'Place of the mission',
  tenCharacter: 'This field requires more than 10 characters',
  informationOnVehicleToBeInspected: 'Information On Vehicle to be Inspected',
  vehicleAnnouncement: 'vehicle announcement',
  vehiclePhoto: 'Vehicle Photo',
  vehiclePhotoCG: 'Vehicle Photo CG',
  sendRequest: 'Send Request',
  changeLanguage: 'Change Language',
  notification: 'Notifications',
  editProfile: 'Edit Profile',
  firstNameText: 'First Name',
  lastNameText: 'Last Name',
  emailAddressText: 'Email Address',
  streetAddressText: 'Street Address',
  cityText: 'City',
  postalCodeText: 'Postal Code',
  countryText: 'Country',
  phoneNumberText: 'Phone Number',
  passwordText: 'Password',
  submit: 'Submit',
  Enter_Email: 'Enter Email Id',
  Enter_Password: 'Enter Password',
  Forget_Password: 'Forget Password',
  SignIn: 'Sign In',
  Dont_Have_Account: "Dont't have an account?",
  Sign_Up: 'Sign Up',
  selectPlace: 'Select Place',
  Individual_User: 'Individual',
  Specialist_User: 'Specialist',
  First_Name: 'First Name',
  Last_Name: 'Last Name',
  Email_Address: 'Email Address',
  Street_Address: 'Street Address',
  City_Address: 'City',
  Postal_Code: 'Postal Code',
  Region_Address: 'Region',
  Country_Address: 'Country',
  Reset_Password: 'Reset Password',
  Phone_Number: 'Phone Number',
  Password: 'Password',
  Next: 'Next',
  Diploma: 'Diploma and CV (photo or attachment)',
  Identity: 'Identity card (front photo or attachment)',
  Identity_Back: 'Identity card (back photo or attachment)',
  Driver_License: "Driver's License (front photo or attachment)",
  Driver_License_Back: "Driver's License (back photo or attachment)",
  RIB: 'RIB (front / back photo or attachment)',
  KIB: 'KBis- situation notice',
  Already_Account: 'Already have an account?',
  vehicleInformation: 'Vehicle Information',
  accept: 'Accept',
  individual: 'Individual',
  specialist: 'Specialist',
  noInspections: `There are no Inpections. How about start adding some ?`,
  addAnInspection: 'Add an Inspection',
  numberSiret: 'Number Siret',
}

const french = {
  language: 'french',
  home: 'Accueil',
  map: 'CARTE',
  scheduleCalendar: 'Calendrier',
  ourTeam: 'Notre équipe',
  settings: 'Paramètre',
  aboutUs: 'À propos de nous',
  logoutText: 'Se déconnecter',
  upcoming: 'A venir',
  newInspection: 'nouvelle inspection',
  pastInspection: 'Inspection passée',
  inspectionDetails: `Détails de l'inspection`,
  tenCharacter: 'Informations sur le véhicule à inspecter',
  vehicleAnnouncement: 'annonce de véhicule',
  vehiclePhoto: 'photo du véhicule',
  vehiclePhotoCG: 'Photo de véhicule CG',
  sendRequest: 'Envoyer une demande',
  changeLanguage: 'Changer de langue',
  notification: 'Notifications',
  editProfile: 'Editer le profil',
  firstNameText: 'Prénom',
  lastNameText: 'Nom de famille',
  emailAddressText: 'Adresse e-mail',
  streetAddressText: 'Adresse de la rue',
  cityText: 'Ville',
  postalCodeText: 'code postal',
  countryText: 'De campagne',
  phoneNumberText: 'Numéro de téléphone',
  passwordText: 'Mot de passe',
  submit: 'Nous faire parvenir',
  Enter_Email: "Entrez l'identifiant de messagerie",
  Enter_Password: 'Entrer le mot de passe',
  Forget_Password: 'Mot de passe oublié',
  SignIn: "S'identifier",
  Dont_Have_Account: "Vous n'avez pas de compte ?",
  Sign_Up: "S'inscrire",
  Individual_User: 'Individuel',
  Specialist_User: 'Spécialisé',
  First_Name: 'Prénom',
  Last_Name: 'Nom de famille',
  Email_Address: 'Adresse e-mail',
  Street_Address: 'Adresse de la rue',
  City_Address: 'Ville',
  Postal_Code: 'Postal Code',
  Region_Address: 'Région',
  Country_Address: 'Pays',
  Reset_Password: 'réinitialiser le mot de passe',
  Phone_Number: 'Numéro de téléphone',
  Password: 'Mot de passe',
  Next: 'Prochaine',
  Diploma: 'Diplôme et CV (photo ou pièce jointe)',
  Identity: "Carte d'identité (photo recto ou pièce jointe)",
  Identity_Back: "Carte d'identité (photo arrière ou pièce jointe)",
  Driver_License: 'Permis de conduire (photo avant ou pièce jointe)',
  Driver_License_Back: 'Permis de conduire (photo arrière ou pièce jointe)',
  RIB: 'RIB (photo recto/verso ou pièce jointe)',
  KIB: 'KBis- avis de situation',
  Already_Account: 'Vous avez déjà un compte?',
  selectPlace: 'Sélectionnez un lieu',
  vehicleInformation: 'Informations sur le Véhicule',
  accept: 'Accept',
  specialist: 'Spécialiste',
  individual: 'Individuel',
  noInspections: `Il n'y a pas d'Inspections. Et si vous commenciez à en ajouter ?`,
  addAnInspection: 'Ajouter une inspection',
  placeOfMission: 'Lieu de la mission',
  numberSiret: 'Numéro Siret',
}

const turkish = {
  language: 'turkish',
  home: 'Ana sayfa',
  map: 'HARİTA',
  scheduleCalendar: 'Takvim Takvimi',
  ourTeam: 'Bizim takım',
  settings: 'Ayarlar',
  aboutUs: 'Hakkımızda',
  logoutText: 'Çıkış Yap',
  upcoming: 'yaklaşan',
  newInspection: 'yeni muayene',
  pastInspection: 'Geçmiş Muayene',
  inspectionDetails: `Muayene Detayları`,
  tenCharacter: `Muayene Edilecek Araç Bilgileri`,
  vehiclePhoto: 'araç Fotoğraf',
  vehicleAnnouncement: 'Araç Fotoğrafı',
  vehiclePhotoCG: 'Araç Fotoğrafı CG',
  sendRequest: 'İstek gönder',
  changeLanguage: 'Dili değiştir',
  notification: 'Bildirim',
  editProfile: 'Profili Düzenle',
  firstNameText: 'İlk adı',
  lastNameText: 'Soy isim',
  emailAddressText: 'E-posta Adresi',
  streetAddressText: 'Sokak adresi',
  cityText: 'Şehir',
  postalCodeText: 'posta kodu',
  countryText: 'Ülke',
  phoneNumberText: 'Telefon numarası',
  passwordText: 'Parola',
  submit: 'Göndermek',
  Enter_Email: 'E-posta Kimliğini Girin',
  Enter_Password: 'E-posta Kimliğini Girin',
  Forget_Password: 'Parolanızı mı unuttunuz',
  SignIn: 'Kayıt olmak',
  Dont_Have_Account: 'Hesabınız yok mu?',
  Sign_Up: 'Üye olmak',
  Individual_User: 'Bireysel',
  Specialist_User: 'Uzman',
  First_Name: 'İlk adı',
  Last_Name: 'Soy isim',
  Email_Address: 'Adresse e-mail',
  Street_Address: 'Açık adres',
  City_Address: 'Şehir',
  Postal_Code: 'posta kodu',
  Region_Address: 'Bölge',
  Country_Address: 'Ülke',
  Reset_Password: 'şifreyi yenile',
  Phone_Number: 'Numéro de téléphone',
  Password: 'Mot de passe',
  Diploma: 'Diploma ve CV (fotoğraf veya ek)',
  Identity: 'Kimlik kartı (ön fotoğraf veya eki)',
  Identity_Back: 'Kimlik kartı (arka fotoğraf veya ek)',
  Driver_License: 'Sürücü Belgesi (ön fotoğraf veya ek)',
  Driver_License_Back: 'Sürücü Belgesi (arka fotoğraf veya ek)',
  RIB: 'RIB (ön / arka fotoğraf veya ek)',
  KIB: 'KBis- durum bildirimi',
  Already_Account: 'Zaten hesabınız var mı?',
  selectPlace: 'Yer Seç',
  Next: 'Sonraki',
  vehicleInformation: 'Araç Bilgisi',
  accept: 'Kabul',
  specialist: 'Uzman',
  individual: 'Bireysel',
  noInspections: `Muayene yoktur. Biraz eklemeye başlamaya ne dersiniz?`,
  addAnInspection: 'İnceleme Ekle',
  placeOfMission: 'Görev yeri',
  numberSiret: 'Numara Siret',
}

export default (state = english, action) => {
  switch (action.type) {
    case 'ENGLISH':
      return english
    case 'FRENCH':
      return french
    case 'TURKISH':
      return turkish
  }
  return state
}
